Repository FAST-HEP/fast-carpenter, pull requests merged in 2019-10, with the labels that each got.

#73 Add support for ND jagged arrays in expressions
  CHANGELOG.md
  fast_carpenter/expressions.py
  fast_carpenter/tree_wrapper.py
  fast_carpenter/version.py
  setup.cfg
  tests/test_expressions.py
Labels: Feature Request, Stage: Variable Defining, enhancement

#77 Fix multi-dimensional jagged array binning
  CHANGELOG.md
  fast_carpenter/summary/binned_dataframe.py
  fast_carpenter/tree_wrapper.py
  fast_carpenter/version.py
  setup.cfg
  tests/summary/test_binned_dataframe.py
Labels: Bug, Feature Request, Stage: BinnedDataFrame

#85 Give "fast-carpenter" to fast-flow to use as the back-end (fixes #84)
  fast_carpenter/__main__.py
Labels: Hacktoberfest

#93 Fix issue 89
  CHANGELOG.md
  fast_carpenter/summary/binned_dataframe.py
  tests/summary/test_binned_dataframe.py
Labels: Bug, Stage: BinnedDataFrame

#96 Add zenodo to README
  README.rst
Labels: Documentation
